### PR TITLE
fix: revert: only consider fully static build on linux 2fcb478

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
This reverts https://github.com/nextstrain/nextclade/commit/2fcb4781ccb1a6c24b49661b865eaf1d04a3f899, which wrongly restricted static linking of dependencies to Linux builds only. As dependency dynamic libraries were now required on macOS, but not redistributed along with the executables, Nextclade was crashing on users' machines, in particular trying to find a dynamic library for Intel TBB.

It went unnoticed during dev and on ci, because these libraries are present in the build directory after the build.

This PR changes build such that macOS binaries are also statically linked and should be self-contained again now.

We might want to implement a smoke test in a clean environment with no build artifacts present other than the executables, to verify that they are truly static and self-contained. This is however challenging for macOS builds, as there are no containers and VMs are quite expensive and clunky to deal with.

Resolves https://github.com/nextstrain/nextclade/issues/595

### CODE REVIEW

**Comment by corneliusroemer** [comment]
> We might want to implement a smoke test in a clean environment with no build artifacts present other than the executables, to verify that they are truly static and self-contained. This is however challenging for macOS builds, as there are no containers and VMs are quite expensive and clunky to deal with.

What stops us from simply downloading build artefacts and test with a simple Github action on macOS? Surely this shouldn't be difficult and takes at most 1 minute per action which is cheap. What am I missing?

**Comment by corneliusroemer** [comment]
Seems to work on Intel, I'd merge and release. Can't make things worse even if it doesn't on ARM. Have to get an ARM to test there.

**Comment by corneliusroemer** [comment]
I do get this error: 
```
fish: Job 1, './nextclade \…' terminated by signal --in-order \… (…)
fish: Job SIGSEGV, 'Address boundary error' terminated by signal  ()
```

**Review by corneliusroemer — APPROVED** [review]
LGTM, tested on Intel Mac and works

**Comment by ivan-aksamentov** [comment]
@corneliusroemer I'll release this fix and then let's address the segmentation fault as a separate issue.

**Pull request merged**
