### PR TITLE
feature: translate minus strand

### PR DESCRIPTION
**Pull request by dnanto**
@ivan-aksamentov 

- #667
- Adding feature to translate the minus strand sequence as defined in the GFF3 file.
- Adds code for complement and reverse complement copied and modified from nextclade
- Adds test for expected translation of minus-strand gene

Test:
```bash
# data
printf ">ref\nATGACTGAATCCACTTAANNNTTAAGTGGATTCAGTCATGTGGATTCAGTCAT\n" > test.ref.fasta
{
  printf ">alt-1\nATGACTGAATCCACTTAANNNTTAAGTGGATTCAGTCATGTGGATTCAGTCAT\n"
  printf ">alt-2\nATGACTGAATCCACTTAANNNTTAAGTGGATTCAGTCATGTGGATTCCATCAT\n"
  printf ">alt-3\nATGACTCATGAATCCACTTAANNNTTACATGGATTCAGTCATGTGGATTCAGTCAT\n"
  printf ">alt-4\nATGACTGAATCCACTTAANNNTTAAGTGGATTCAGTCATGTGGATTCAGTCAT\n"
  printf ">alt-5\nATGACTGAATCCACTTAANNNTTAAGTGGATTCAGTCATGTGGATTCAGTAGTCAT\n"
  printf ">alt-6\nATGACTGAATCCACTTAANNNTTAAGTAGTGGATTCAGTCATGTGGATTCAGTCAT\n"
} > test.seq.fasta
{
  echo . . gene 1 15 . + 0 gene_name=fwd
  echo . . gene 25 39 . - 0 gene_name=rev
} | tr ' ' '\t' > test.gff3

# run this branch
.build/Release-Static/packages/nextalign_cli/nextalign-Linux-x86_64 \
  -j 1 \
  --in-order \
  -i test.seq.fasta \
  -r test.ref.fasta \
  --include-reference \
  --genes=fwd,rev \
  --genemap test.gff3 \
  --output-dir test1 \
  --min-length 33

# run v1.8.0
conda run -n nextalign \
  nextalign \
    -j 1 \
    --in-order \
    -i test.seq.fasta \
    -r test.ref.fasta \
    --include-reference \
    --genes=fwd,rev \
    --genemap test.gff3 \
    --output-dir test2 \
    --min-length 33
```

Compare:
```
find test1 -type f | sort | while read -r ele; do md5sum "$ele" "${ele/test1/test2}";  done
947cac2f4db72ee50a3be20016ace935  test1/test.seq.aligned.fasta
947cac2f4db72ee50a3be20016ace935  test2/test.seq.aligned.fasta
9653f08f9cc1deaece452c7157283a69  test1/test.seq.errors.csv
9653f08f9cc1deaece452c7157283a69  test2/test.seq.errors.csv
1cedcb45dea34357a34cce2081903dff  test1/test.seq.gene.fwd.fasta
1cedcb45dea34357a34cce2081903dff  test2/test.seq.gene.fwd.fasta
25a2dc8662a0d687ddd740608ceea6c0  test1/test.seq.gene.rev.fasta
7c3a00fd8cc505b39b4a80b3604cf6fa  test2/test.seq.gene.rev.fasta
a8d6c903c521c612e38294e8b4fef9fd  test1/test.seq.insertions.csv
a8d6c903c521c612e38294e8b4fef9fd  test2/test.seq.insertions.csv
```

Reverse sequence md5 differ, output is corrected with this branch:
```
paste test1/test.seq.gene.rev.fasta test2/test.seq.gene.rev.fasta
>ref	>ref
MTEST	SGFSH
>alt-1	>alt-1
MTEST	SGFSH
>alt-2	>alt-2
MTEST	SGFSH
>alt-3	>alt-3
MTESM	HGFSH
>alt-4	>alt-4
MTEST	SGFSH
>alt-5	>alt-5
MTEST	SGFSH
>alt-6	>alt-6
MTEST	SGFSH
```

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@dnanto This looks fantastic, thanks so much!

I will let my science team to also take a look.
I wish we had some real-world data to also test it on what people might be feeding into Nextalign.

There is a few bugs on master that will need to be resolved first. I'll be prioritizing that, but will come back to this PR shortly after.

**Comment by dnanto** [comment]
@ivan-aksamentov Nice! Glad I could help.

I'm happy to share my data. The following is a script that will download HAdV-A genomes and run the analysis.

Note: I curated the GFF3 file based on the CDS regions to normalize the names and add a suffix to disambiguate splicing effects. Seems to work nicely...

```bash
#!/usr/bin/env bash

# test on HAdV-A

# reference
efetch -db nuccore -id NC_001460.1 -format fasta > A.ref.fasta

# sequences
echo \
  GU191019.1 KX868289.2 JF964962.1 KF268119.1 MW686761.1 \
  MW686760.1 MG872324.1 MW686759.1 MW686757.1 MW686772.1 \
  MW686758.1 MW686764.1 MW686765.1 MW686766.1 MW686767.1 \
  MG872075.1 MW686762.1 MW686763.1 MW686777.1 MW686778.1 \
  MW686779.1 MW686780.1 MW686783.1 MW686769.1 MW686781.1 \
  MW686775.1 MW686774.1 MW686776.1 MW686784.1 MW686768.1 \
  MW686771.1 MW686773.1 MW686782.1 | \
  efetch -db nuccore -format fasta > A.seq.fasta

# GFF3
cat > A.cds.gff3 <<GFF
##sequence-region NC_001460.1 1 34125
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=129875
NC_001460.1	RefSeq	gene	503	1069	.	+	0	gene_name=E1A.1
NC_001460.1	RefSeq	gene	1145	1375	.	+	2	gene_name=E1A.2
NC_001460.1	RefSeq	gene	1542	2033	.	+	0	gene_name=19K.1
NC_001460.1	RefSeq	gene	1847	3295	.	+	0	gene_name=55K.1
NC_001460.1	RefSeq	gene	3374	3808	.	+	0	gene_name=IX.1
NC_001460.1	RefSeq	gene	13340	13348	.	-	0	gene_name=pol.1
NC_001460.1	RefSeq	gene	4953	8513	.	-	0	gene_name=pol.2
NC_001460.1	RefSeq	gene	13340	13348	.	-	0	gene_name=TP.1
NC_001460.1	RefSeq	gene	8312	10228	.	-	0	gene_name=TP.2
NC_001460.1	RefSeq	gene	3844	5202	.	-	0	gene_name=IVa2.1
NC_001460.1	RefSeq	gene	29368	31131	.	+	0	gene_name=IV.1
NC_001460.1	RefSeq	gene	22695	25043	.	+	0	gene_name=100K.1
NC_001460.1	RefSeq	gene	24763	25077	.	+	0	gene_name=33K.1
NC_001460.1	RefSeq	gene	25257	25556	.	+	2	gene_name=33K.2
NC_001460.1	RefSeq	gene	24763	25311	.	+	0	gene_name=22K.1
NC_001460.1	RefSeq	gene	25612	26313	.	+	0	gene_name=VIII.1
NC_001460.1	RefSeq	gene	16843	17640	.	+	0	gene_name=VI.1
NC_001460.1	RefSeq	gene	17740	20499	.	+	0	gene_name=II.1
NC_001460.1	RefSeq	gene	20525	21145	.	+	0	gene_name=protease.1
NC_001460.1	RefSeq	gene	13394	14887	.	+	0	gene_name=III.1
NC_001460.1	RefSeq	gene	14902	15468	.	+	0	gene_name=VII.1
NC_001460.1	RefSeq	gene	15509	16543	.	+	0	gene_name=V.1
NC_001460.1	RefSeq	gene	16568	16786	.	+	0	gene_name=X.1
NC_001460.1	RefSeq	gene	7731	8138	.	+	0	gene_name=13.6K.1
NC_001460.1	RefSeq	gene	9370	9390	.	+	0	gene_name=13.6K.2
NC_001460.1	RefSeq	gene	10428	11549	.	+	0	gene_name=52K.1
NC_001460.1	RefSeq	gene	11570	13318	.	+	0	gene_name=IIIa.1
NC_001460.1	RefSeq	gene	21215	22669	.	-	0	gene_name=DBP.1
NC_001460.1	RefSeq	gene	26313	26630	.	+	0	gene_name=12.5K.1
NC_001460.1	RefSeq	gene	26584	27378	.	+	0	gene_name=CR1-alpha.1
NC_001460.1	RefSeq	gene	27381	28187	.	+	0	gene_name=CR1-beta.1
NC_001460.1	RefSeq	gene	28207	28482	.	+	0	gene_name=RID-alpha.1
NC_001460.1	RefSeq	gene	28479	28811	.	+	0	gene_name=RID-beta.1
NC_001460.1	RefSeq	gene	28804	29190	.	+	0	gene_name=14.7K.1
NC_001460.1	RefSeq	gene	29204	29356	.	-	0	gene_name=U.1
NC_001460.1	RefSeq	gene	32168	32311	.	-	0	gene_name=ORF6slash7.1
NC_001460.1	RefSeq	gene	31183	31416	.	-	0	gene_name=ORF6slash7.2
NC_001460.1	RefSeq	gene	31436	32311	.	-	0	gene_name=34K.1
NC_001460.1	RefSeq	gene	32244	32606	.	-	0	gene_name=ORF4.1
NC_001460.1	RefSeq	gene	32613	32963	.	-	0	gene_name=ORF3.1
NC_001460.1	RefSeq	gene	32960	33355	.	-	0	gene_name=ORF2.1
NC_001460.1	RefSeq	gene	33387	33770	.	-	0	gene_name=ORF1.1
GFF

# align (using this branch)
docker container run -v "$(pwd)":/home --interactive --tty --rm ubuntu \
  /home/.build/Release-Static/packages/nextalign_cli/nextalign-Linux-x86_64 \
    -j 14 \
    --in-order \
    -i /home/A.seq.fasta \
    -r /home/A.ref.fasta \
    --genes=100K.1,12.5K.1,13.6K.1,13.6K.2,14.7K.1,19K.1,22K.1,33K.1,33K.2,34K.1,52K.1,55K.1,CR1-alpha.1,CR1-beta.1,DBP.1,E1A.1,E1A.2,II.1,III.1,IIIa.1,IV.1,IVa2.1,IX.1,ORF1.1,ORF2.1,ORF3.1,ORF4.1,ORF6slash7.1,ORF6slash7.2,RID-alpha.1,RID-beta.1,TP.1,TP.2,U.1,V.1,VI.1,VII.1,VIII.1,X.1,pol.1,pol.2,protease.1 \
    --genemap /home/A.cds.gff3 \
    --output-dir /home/A \
    --nuc-seed-length 27 \
    --nuc-seed-spacing 10 \
    --max-indel 700
```

Output:
```
(bio) dnanto@compu nextclade % bash -x hadv.sh 
+ efetch -db nuccore -id NC_001460.1 -format fasta
+ echo GU191019.1 KX868289.2 JF964962.1 KF268119.1 MW686761.1 MW686760.1 MG872324.1 MW686759.1 MW686757.1 MW686772.1 MW686758.1 MW686764.1 MW686765.1 MW686766.1 MW686767.1 MG872075.1 MW686762.1 MW686763.1 MW686777.1 MW686778.1 MW686779.1 MW686780.1 MW686783.1 MW686769.1 MW686781.1 MW686775.1 MW686774.1 MW686776.1 MW686784.1 MW686768.1 MW686771.1 MW686773.1 MW686782.1
+ efetch -db nuccore -format fasta
+ cat
++ pwd
+ docker container run -v /Users/dnanto/GitHub/nextclade:/home --interactive --tty --rm ubuntu /home/.build/Release-Static/packages/nextalign_cli/nextalign-Linux-x86_64 -j 14 --in-order -i /home/A.seq.fasta -r /home/A.ref.fasta --genes=100K.1,12.5K.1,13.6K.1,13.6K.2,14.7K.1,19K.1,22K.1,33K.1,33K.2,34K.1,52K.1,55K.1,CR1-alpha.1,CR1-beta.1,DBP.1,E1A.1,E1A.2,II.1,III.1,IIIa.1,IV.1,IVa2.1,IX.1,ORF1.1,ORF2.1,ORF3.1,ORF4.1,ORF6slash7.1,ORF6slash7.2,RID-alpha.1,RID-beta.1,TP.1,TP.2,U.1,V.1,VI.1,VII.1,VIII.1,X.1,pol.1,pol.2,protease.1 --genemap /home/A.cds.gff3 --output-dir /home/A --nuc-seed-length 27 --nuc-seed-spacing 10 --max-indel 700
[ WARN] Nextalign: Warning: in sequence "MG872075.1 UNVERIFIED: Human mastadenovirus A strain human/UK/GOSH_2011_Adv31/ sequence": Unable to align: no seed matches. Note that this sequence will be excluded from results.
```

**Comment by rneher** [comment]
thanks, @dnanto. This looks great! I was slightly worried that the automatic bandwidth and shift detection might require adaptation, but thinking it through I convinced myself it should work without problems.

**Review by rneher — APPROVED** [review]

**Comment by ivan-aksamentov** [comment]
Thanks again @dnanto!

Do you mind if we add the sample that you selected to our collection of sample data? If so, could you please double-check it for correctness and add modifications, if necessary?

**Comment by dnanto** [comment]
@ivan-aksamentov Your welcome! I don't mind, I'll double check as well...

**Pull request merged**
