### PR TITLE
Support reverse (minus) strands

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
This PR adds changes that allow for supporting of reverse (negative) strands in viral genomes.

### CODE REVIEW

**Comment by rneher** [comment]
Thanks, Ivan. This seems to work as expected. The only remaining issue now is that the nucleotide numbering should go in reverse and a hint for the user that this is the reverse complement:

image

**Comment by rneher** [comment]
the nucleotide numbering still needs adjusting:
image

note that the mutated base is 54126 and the numbering needs to decrease from left to right (reverse strand...)

**Comment by ivan-aksamentov** [comment]
@rneher Yes, that's in the works, along with some refactoring

**Comment by rneher** [comment]
I am getting null-pointer exception in the preview app.

**Comment by corneliusroemer** [comment]
Still getting that null pointer error
image

**Comment by ivan-aksamentov** [comment]
The real error is in the browser console. The null pointer error here is an emulation of Rust panics (web platform does not have a concept of panics).

In this case the panic is caused by an array overrun due to mistakes in calculating indices. It's not very useful to run the web app before the algorithm is fixed.

**Comment by rneher** [comment]
I added tests and fixed a couple of errors.

**Comment by rneher** [comment]
I'll dig into the actual frame shift code later.

**Pull request merged**
