### PR TITLE
Fetch custom (community) datasets from GitHub and other locations

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
Resolves: https://github.com/nextstrain/nextclade/issues/1024

This PR adds `dataset-url` URL parameter to Nextclade Web. This parameter accepts a URL to a remote directory containing files constituting a single [Nextclade dataset](https://docs.nextstrain.org/projects/nextclade/en/stable/user/datasets.html). If this parameter is provided, Nextclade Web will skip downloading the usual dataset index from the default dataset server and will use a single dataset from the specified URL instead.

The following files are expected in the remote directory (using the same naming convention as for all other datasets):

```
genemap.gff
primers.csv
qc.json
reference.fasta
tree.json
virus_properties.json
tag.json (optional)
sequences.fasta (optional)
```

The `tag.json` file is optional and is used to retrieve dataset name and other decorative attributes to be displayed in the user interface. If it si missing, the placeholder values are used instead.

The `sequences.fasta` file is optional and if provided, allows for "Load example" link to work. When clicked, it will download and analyze the provided `sequences.fasta`. Otherwise, input sequences can be provided as usual - manually or with `input-fasta` URL param.

### Fetching single dataset from GitHub using repo URL

The `dataset-url` URL param allows fetching from GitHub repositories using full URL to a directory of a repo:

```
https://github.com/org/repo
https://github.com/org/repo/tree/branch
https://github.com/org/repo/tree/branch/path/to/file
```

If a branch name is not specified, the default branch name is queried from GitHub REST API (subject to rate limits).

In order to obtain the correct URL: open GitHub website, navigate to the directory where your dataset files reside, then copy URL from browser's address bar.

Example: https://nextclade-git-feat-datasets-from-github-nextstrain.vercel.app/?dataset-url=https://github.com/nextstrain/nextclade_data/tree/master/data/datasets/flu_yam_ha/references/JN993010/versions/2022-07-27T12:00:00Z/files

### Fetching single dataset from GitHub repo shortcut

The `dataset-url` URL param also accepts shortcuts instead of full URLs for GitHub repos:

```
github:owner/org/repo
github:owner/org/repo/path/to/file
github:owner/org/repo@branch@
github:owner/org/repo@branch@/path/to/file

gh:owner/org/repo
gh:owner/org/repo/path/to/file
gh:owner/org/repo@branch@
gh:owner/org/repo@branch@/path/to/file
```

If a branch name is not specified, the default branch name is queried from GitHub REST API (subject to rate limits).

Example: https://nextclade-git-feat-datasets-from-github-nextstrain.vercel.app/?dataset-url=github:nextstrain/nextclade_data@master@/data/datasets/flu_yam_ha/references/JN993010/versions/2022-07-27T12:00:00Z/files

### Fetching single dataset from any location using directory URL

The new `dataset-url` URL param allows fetching from any remote location. Server should be publicly accessible and have CORS enabled.

Example: https://nextclade-git-feat-datasets-from-github-nextstrain.vercel.app/?dataset-url=https://data.clades.nextstrain.org/datasets/flu_yam_ha/references/JN993010/versions/2022-07-27T12:00:00Z/files

Example: if you run a local file server, you can use `localhost` URLs as well: https://nextclade-git-feat-datasets-from-github-nextstrain.vercel.app/?dataset-url=http://localhost:27722/datasets/flu_yam_ha/references/JN993010/versions/2022-07-27T12:00:00Z/files

### CODE REVIEW

**Comment by corneliusroemer** [comment]
Excellent stuff! We could possibly make sequences.fasta optional - or would this make things tricky as the frontend assumes there are always sequences to load?

**Comment by ivan-aksamentov** [comment]
@corneliusroemer I've made `sequences.fasta` optional.

Also, since yesterday, I revamped things a little:

 - there is now only `dataset-url` parameter - it detects which URL is passed in a smart way (hopefully)
 - github shortcuts are now accepted

In order for pretty dataset names to appear in the UI we need to copy `attributes` into `tag.json` when preparing it in the data repo.

Also, `preferredGene` and `geneOrderPreference` which control twhich genes are displayed in sequence view and in which order listed, they are also in `tag.json`. This was a mistake. We should move them to `virus_properties.json`.

Please review, try to break it, and let me know if you have further suggestions.

**Comment by corneliusroemer** [comment]
This is very cool, to make it a bit nicer for Github stuff, it would be nice if it took a simplified URL and reformatted automatically.
Rather than `https://nextclade-git-feat-datasets-from-github-nextstrain.vercel.app/?dataset-url=https://github.com/nextstrain/nextclade_data/tree/bcc638e140ecb8d3c452d186d84596de22ee343b/data/datasets/sars-cov-2-21L/references/BA.2/versions/2022-10-19T12:00:00Z/files/` I'd love to just provide:
`nextstrain/nextclade_data@BRANCH/COMMIT/TAG:data/datasets/sars-cov-2-21L/references/BA.2/versions/2022-10-19T12:00:00Z/files/`

**Review by corneliusroemer — APPROVED** [review]
I've tested and it works in many cases. There could be bugs but nothing that doesn't warrant including in master immediately - and fixing later on the go.

Amazing work @ivan-aksamentov

**Pull request merged**
