### PR TITLE
feat: add sample data for hAdv-A

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
This adds sample data for Nextalign for Human Adenovirus A.

Extracted with modifications from this message by @dnanto 
https://github.com/nextstrain/nextclade/pull/673#issuecomment-1007488135

### CODE REVIEW

**Comment by corneliusroemer** [comment]
What am I expected to see? Adenovirus added as an extra dataset? Doesn't look like it for me 😬

**Comment by ivan-aksamentov** [comment]
@corneliusroemer it's a "nextalign" dataset if you will

**Comment by corneliusroemer** [comment]
Should I see it here? Or how would it manifest? Because I can't find anything 👀 
image

**Comment by ivan-aksamentov** [comment]
@corneliusroemer nono, it is not related to Nextclade at all. There are only sequences.fasta, reference.fasta and genemap.gff, so not enough to run Nextclade. 

I only add it to the collection of Nextalign data in the data/ directory of the repo, alongside enterovirus, zika and flus for which we don't have a Nextclade dataset (a tree basicaly) either.

I'd enjoy of course having a tree and calling it a Nextclade dataset, because Adenoviridae are so different from what we currently work on.

This is mostly for dev and curiosity purposes: to have some samples ready available and to periodically check against them, so that we know we are moving towards the goal of making Nextclade supporting many different viruses.

**Comment by dnanto** [comment]
@ivan-aksamentov @corneliusroemer

I'm currently experimenting with this data set, but I believe that it is valid for testing. Though, I want to mention that these are CDS regions that I've aliased as genes, which I think might be necessary for Nextalign compatibility. I figured that one would want to align codons of the CDS regions instead of entire genes when alternative splicing is a feature (for [some viruses](https://viralzone.expasy.org/1943)). So, this is what motivated appending a suffix to disambiguate the entries. If there are two CDS entries with the same name, then nextalign will override the sequence entry. Anyway, I'll work on a branch to see if I can account for this behavior, that is, if it makes sense or isn't too complex...

Also, I do have a goal of making a full nextclade dataset for HAdV. The current paper I'm working on doesn't require it so far, but I see a potential paper for genotyping purposes, at least for HAdV. Either way, I'm glad to contribute future datasets here and would love to host a complete nextstrain build once the current paper is done.

**Comment by rneher** [comment]
I think we would need to put in some thought on how to handle splicing and multipartite transcripts.

**Comment by rneher** [comment]
For long genomes like that, I think we would also want to optimize the bandwidth determination for the alignment and the seedmatching.

**Pull request merged**
