### PR TITLE
feat: set gap alignment to "left" by default

### PR DESCRIPTION
**Pull request by ivan-aksamentov**

### CODE REVIEW

**Comment by corneliusroemer** [comment]
Not blocking but it would be nice if we could indicate the default value in the CLI help. Right now it says "possible values left, right" but not which one is the default.

**Comment by ivan-aksamentov** [comment]
@corneliusroemer I made it as follows now:

```
      --gap-alignment-side <GAP_ALIGNMENT_SIDE>
          Whether to align gaps on the left or right side if equally parsimonious. Default: left
          
          [possible values: left, right]

```

**Comment by ivan-aksamentov** [comment]
This text could be incorrect though depending on how dataset is configured, which we have no way of telling at the time of printing help text.

**Comment by corneliusroemer** [comment]
Thanks, that's great! I think it's ok that pathogen json can overrides default and CLI won't show. The CLI just shows the bare default that applies in case nothing overrides.

**Comment by ivan-aksamentov** [comment]
@corneliusroemer We have a failing test now. Can you help me with it?
https://github.com/nextstrain/nextclade/actions/runs/7477824073/job/20351461502?pr=1377#step:7:397

**Comment by rneher** [comment]
The validating the path matrices is a bit tricky, but it all looks correct to me.

**Pull request merged**
