### PR TITLE
update tree and snakemake profile

### PR DESCRIPTION
**Pull request by rneher**
This PR only updates the tree asset and makes minor changes in the profile for the augur run.

### CODE REVIEW

**Comment by rneher** [comment]
I need to polish the tree some more... will do tomorrow.

**Comment by rneher** [comment]
somehow the load examples doesn't work for me here. 

image
Let me confirm whether I have the same problem locally on master.

**Comment by rneher** [comment]
yes, same issue on local master and https://master.clades.nextstrain.org/

**Comment by ivan-aksamentov** [comment]
@rneher Should be fixed in #223

**Comment by ivan-aksamentov** [comment]
If you have a second, consider also #109

**Pull request merged**
