### PR TITLE
perf: use faster fasta parser implementation

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
This improves runtime performance of Nextalign and Nextclade CLI.

The speedup is achieved by using a faster FASTA parser. As a base I used code from kseqpp from Ali Ghaffaari (`@cartoonist`): https://github.com/cartoonist/kseqpp

We are loosing these features:

 - Sequence names are no longer tracked and deduplicated. It required storing a map of all sequence names and lookups into this map on each new sequence. So a map of 5M items for GISAID. This feature is a  "nice-to-have" and I think we can sacrifice it.
 - Plain text files are not supported by this parser.
 - Hard to test, because it uses lower-level C APIs to read files and parsing logic intertwined with I/O. Old tests are commented out for now.
 - Requires UNIX-specifics (`unistd.h` and `fcntl.h`). But we only ship Linux and MacOS, so this should be fine. If Windows release will be needed, we can use a second implementation there conditionally.

### Benchmarks

Setup:

 - AWS EC2 c5.24xlarge (96 cores @ 3.6 GHz, 192GiB RAM)
 - SSD: gp2 1TB 3000 IOPS
 - Ubuntu 20.04
 - 100k randomly sampled GISAID sequences

Results:

```
|-------------|---------------------|---------------------|---------|
|             |   Wall clock time   |  Throughput, seq/s  |         |
|-------------|-----------|---------|-----------|---------|---------|
|             |   before  |   after |   before  |  after  | speedup |
|-------------|-----------|---------|-----------|---------|---------|
| Nextalign   |   5m 09s  |     51s |      324  |    1933 |   6.05x |
| Nextclade   |   6m 15s  |  3m 47s |      266  |     440 |   1.65x |
|-------------|-----------|---------|-----------|---------|---------|

```

### Scaling

Both tools now scale nicely to a large number of cores.

Before:
before

After:
after

### Try it:

Staging CLI executables are under "Artifacts" tab on the page for each architecture:
https://app.circleci.com/pipelines/github/nextstrain/nextclade/1873/workflows/d8c194a3-6dbe-4f7b-929a-5a2433b1c470

### Repro

Prepare sample data:

```bash
seqkit sample --proportion=0.02 gisaid.fasta | seqkit head --number=100000 -o gisaid-100k.fasta
seqkit stats gisaid-100k.fasta
```

Alias for time measurement:

```bash
alias TIME="/usr/bin/time -f 'Wall clock time:         %E\nMaximum resident memory: %M KB\n'"
```

Get executables:

```bash

curl -fsSL https://github.com/nextstrain/nextclade/releases/download/1.5.1/nextalign-Linux-x86_64 -o nextalign-1.5.1

curl -fsSL https://github.com/nextstrain/nextclade/releases/download/1.5.1/nextclade-Linux-x86_64 -o nextclade-1.5.1

curl -fsSL https://1078-271799467-gh.circle-artifacts.com/0/nextalign-Linux-x86_64 -o nextalign-faster

curl -fsSL https://1078-271799467-gh.circle-artifacts.com/0/nextclade-Linux-x86_64 -o nextclade-faster

```

Get dataset:

```bash
nextclade dataset get --name=sars-cov-2 --output-dir=data/
```

Run:

```bash
reset; TIME ./nextalign-1.5.1 --sequences=gisaid-100k.fasta --reference=data/reference.fasta --genemap=data/genemap.gff --genes=E,M,N,ORF1a,ORF1b,ORF3a,ORF6,ORF7a,ORF7b,ORF8,ORF9b,S --output-dir=tmp/ --output-basename=nextalign --include-reference --silent

reset; TIME ./nextalign-faster --sequences=gisaid-100k.fasta --reference=data/reference.fasta --genemap=data/genemap.gff --genes=E,M,N,ORF1a,ORF1b,ORF3a,ORF6,ORF7a,ORF7b,ORF8,ORF9b,S --output-dir=tmp/ --output-basename=nextalign --include-reference --silent

reset; TIME ./nextclade-1.5.1 --input-fasta=gisaid-100k.fasta --input-dataset=data/ --output-tsv=tmp/nextclade.tsv --output-dir=tmp/ --output-basename=nextclade --include-reference --silent

reset; TIME ./nextclade-faster --input-fasta=gisaid-100k.fasta --input-dataset=data/ --output-tsv=tmp/nextclade.tsv --output-dir=tmp/ --output-basename=nextclade --include-reference --silent
```

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
I ran some additional numbers, to see how it scales with number of threads:


[bench.csv](https://github.com/nextstrain/nextclade/files/7633582/bench.csv)
[bench.sh.zip](https://github.com/nextstrain/nextclade/files/7633587/bench.sh.zip)

**Comment by corneliusroemer** [comment]
Amazing! Finally the fasta parsing bottleneck is removed! Same graph for
Nextclade would be interesting too.

**Comment by ivan-aksamentov** [comment]
Nextclade's improvement is less impressive. But I have a few ideas for later.

**Comment by ivan-aksamentov** [comment]
I brought back the slower parser, because we cannot use the new parser (which can only read from file) in the WebAssembly module (which only has string inputs). Later we might figure out how to adapt the new parser to string inputs.

**Comment by ivan-aksamentov** [comment]
I just verified on 100k sequences that both pairs of tools produce byte-identical results. So this PR and executables are ready to be reviewed.

**Comment by rneher** [comment]
I just gave this a go and it worked fine. I reproduce the `nextalign` speed up with 8 threads.

**Comment by ivan-aksamentov** [comment]
I verified once again that this is stable on 1M sequence dataset, and also benchmarked against v1.6.0:

```
experiment_name,problem_size,num_jobs,wall_seconds,max_mem_kb
nextalign-1.6.0,100000,96,315.11,10548
nextalign-1.6.0,100000,80,315.09,10460
nextalign-1.6.0,100000,64,315.67,10516
nextalign-1.6.0,100000,48,315.52,10516
nextalign-1.6.0,100000,32,315.56,10492
nextalign-1.6.0,100000,16,316.78,10556
nextalign-1.6.0,100000,8,429.80,10492
nextalign-faster,100000,96,65.03,10628
nextalign-faster,100000,80,65.05,10572
nextalign-faster,100000,64,66.80,10548
nextalign-faster,100000,48,75.02,10560
nextalign-faster,100000,32,100.20,10544
nextalign-faster,100000,16,186.60,10632
nextalign-faster,100000,8,346.59,10460
nextclade-1.6.0,100000,96,389.74,10488
nextclade-1.6.0,100000,80,392.52,10540
nextclade-1.6.0,100000,64,387.37,10404
nextclade-1.6.0,100000,48,388.20,10380
nextclade-1.6.0,100000,32,478.83,10516
nextclade-1.6.0,100000,16,827.01,10460
nextclade-1.6.0,100000,8,1541.98,10456
nextclade-faster,100000,96,220.94,10444
nextclade-faster,100000,80,239.25,10556
nextclade-faster,100000,64,263.26,10572
nextclade-faster,100000,48,313.00,10468
nextclade-faster,100000,32,417.64,10552
nextclade-faster,100000,16,760.09,10444
nextclade-faster,100000,8,1435.72,10380
```

Merging

**Pull request merged**
